mod aggregates;
mod application_registry;
pub(crate) mod desktop;
mod desktop_environment;
// mod desktop_interaction;
// mod desktop_presenter;
mod desktop_system;
mod event_router;
mod event_sourcing;
mod focus_path;
mod focus_target;
mod instance_manager;
mod instance_presenter;
mod layout;
mod projects;

pub use aggregates::*;
pub use application_registry::Application;
pub use desktop::Desktop;
pub use desktop_environment::*;
// pub use desktop_interaction::*;
// pub use desktop_presenter::DesktopPresenter;
pub use desktop_system::DesktopTarget;
pub use event_router::{EventRouter, EventTransition, HitTester};
