name: 'qa'
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  qa:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: 'Toolchain'
      uses: dtolnay/rust-toolchain@stable

    - name: 'Clippy'
      run: cargo clippy --all-targets -- -D warnings

    - name: 'Test'
      run: cargo test --all-targets

  formatting:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: 'Install toolchain'
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt

    - name: 'Check Formatting'
      run: | 
        cargo fmt -- --check
